### ISSUE TITLE
Is it possible to post to the channel instead of being scoped to the issuing user?

### ISSUE THREAD

**Issue by peacefulrespite** [strattonw/slackrandom#1]
Thank you for building and hosting such a neat project!

My question is, when I issue the `/random` command, slackbot returns it so that only I can see the response. Is it possible to return it so all those in the channel can see it?

I checked out the project source, Slack docs, and integration settings, but nothing stood out as what causes the message to get scoped.

A screenshot of what I am talking about:

![screen shot 2015-05-27 at 1 50 20 pm](https://cloud.githubusercontent.com/assets/928367/7843672/2ac45e12-0479-11e5-9524-9c7e06867419.png)

**Comment by strattonw** [comment]
Not at the moment but it is something that I am looking into adding in the future

**Comment by brettchalupa** [comment]
@strattonw thank you! Shall I close this or do you want to keep it open until it is implemented? :smile:

**Comment by strattonw** [comment]
@brettchalupa Keep it open :)
